export const DESTINATIONS_LOADING = 'DESTINATIONS_LOADING';
export const ADD_DESTINATIONS = 'ADD_DESTINATIONS';
export const DESTINATIONS_FAILED = 'DESTINATIONS_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const SPONSORS_LOADING = 'SPONSORS_LOADING';
export const ADD_SPONSORS = 'ADD_SPONSORS';
export const SPONSORS_FAILED = 'SPONSORS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE'; 


export const ADD_REVIEW = 'ADD_REVIEW';