export const DESTINATIONS_LOADING = 'DESTINATIONS_LOADING';
export const ADD_DESTINATIONS = 'ADD_DESTINATIONS';
export const DESTINATIONS_FAILED = 'DESTINATIONS_FAILED';

export const ADD_REVIEWS = 'ADD_REVIEWS';
export const REVIEWS_FAILED = 'REVIEWS_FAILED';

export const ADVENTURES_LOADING = 'ADVENTURES_LOADING';
export const ADD_ADVENTURES = 'ADD_ADVENTURES';
export const ADVENTURES_FAILED = 'ADVENTURES_FAILED';

export const SPONSORS_LOADING = 'SPONSORS_LOADING';
export const ADD_SPONSORS = 'ADD_SPONSORS';
export const SPONSORS_FAILED = 'SPONSORS_FAILED';
 


export const ADD_REVIEW = 'ADD_REVIEW';